name: Purge cache

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest

    outputs:
      any_modified: ${{ steps.changed-files.outputs.any_modified }}
      all_changed_and_modified_files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: "true"
          files: |
            blog/**
            snippets/**

      - name: List Modified Files
        if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified"
          done

  rebuild-index:
    name: Rebuild Index
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.any_modified == 'true' }}
    runs-on: ubuntu-latest

    outputs:
      index_rebuilt: ${{ steps.auto-commit-action.outputs.changes_detected }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_READWRITE }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Rebuild Index
        run: "deno run --allow-read --allow-write src/rebuild-index.ts"

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto-commit-action
        with:
          commit_message: Rebuild index
          file_pattern: index.json

  purge-cache:
    name: Purge Cache
    needs: [changed-files, rebuild-index]
    if: ${{ needs.changed-files.outputs.any_modified == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Purge Modified Files
        run: "deno run --allow-net src/purge-cache.ts --paths '${{ needs.changed-files.outputs.all_changed_and_modified_files }}'${{ (needs.rebuild-index.outputs.index_rebuilt == 'true' && ' --index-rebuilt') || '' }} --token ${{ secrets.CF_TOKEN }} --zone ${{ secrets.CF_ZONE }}"
