name: Purge cache

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  purge:
    name: Purge Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.1
        
      - name: List added files
        run: echo ${{ steps.changed-files.outputs.added_files }}
