name: Purge cache

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  purge:
    name: Purge Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34.5.1
        with:
          json: "true"
          files: |
            snippets/**

      - name: List modified files
        run: |
          for file in ${{ steps.changed-files.outputs.modified_files }}; do
            echo "$file was modified"
          done

      - name: Setup Deno
        if: ${{ steps.changed-files.outputs.any_modified }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Purge modified files
        if: ${{ steps.changed-files.outputs.any_modified }}
        run: "deno run src/purge-cache.ts --paths '{ \"files\": [\"https://zachyoung.dev/snippets\", \"https://zachyoung.dev/snippets?_data=routes%snippets\"] }'"

