name: Purge cache

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Retrieve the current commit

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            blog/**
            snippets/**
            index.json

      - name: List Modified Files
        if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was modified"
          done

  rebuild-index:
    name: Rebuild Index
    if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
    needs: [changed-files]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_READWRITE }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Rebuild Index
        run: "deno run --allow-read --allow-write src/rebuild-index.ts"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Rebuild index
          file_pattern: index.json

  purge-cache:
    name: Purge Cache
    if: ${{ steps.changed-files.outputs.any_modified == 'true' }}
    needs: [changed-files, rebuild-index]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Retrieve the proceeding commit if index was rebuilt, otherwise retrieve current commit
          # https://github.com/actions/runner/issues/409
          fetch-depth: ${{ (steps.auto-commit-action.outputs.changes_detected == 'true' && 2) || 0 }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Purge Modified Files
        run: |
          "deno run --allow-net src/purge-cache.ts --paths '${{ steps.changed-files.outputs.all_changed_and_modified_files }} ${{ (steps.auto-commit-action.outputs.changes_detected == 'true' && 'index.json') || '' }}' --token ${{ secrets.CF_TOKEN }} --zone ${{ secrets.CF_ZONE }}"
